export const titlePtbr = 'Desenvolvedora de Software Front-End';

export const aboutMePtBr = 'Sobre mim'
export const projectsPtBr = 'Projetos'

export const detailsPtBr = '<p>Endereço: Eindhoven - Países Baixos</p><p>E-mail: brunapessoa.bpm@gmail.com</p>'

export const aboutTxtPtBr = '<p>Desenvolvedora Front-end brasileira, focada na criação de interfaces modernas, responsivas e centradas no usuário.</p><p>Desenvolvo aplicações web funcionais e bem estruturadas utilizando HTML, CSS, JavaScript, React e Tailwind, com atenção aos detalhes.</p><p>Após 5 anos na área jurídica, levo para a tecnologia forte pensamento analítico, organização e uma mentalidade voltada para resolução de problemas.</p>'

export const projectsTxtPtBr = 'Você pode acessar meus projetos:<p>'

export const planBDescPtBr = '<p><abbr title="HTML 5"><img src="images/icons/html5-200.png" alt="html-logo" class="skillsIcons"></abbr><abbr title="CSS 3"><img src="images/icons/css3-200.png" alt="css-logo" class="skillsIcons"></abbr><abbr title="JavaScript"><img src="images/icons/javascript.svg" alt="js-logo" class="skillsIcons jsIcon"></abbr></p><p>Aplicação de planejamento de treinos client-side com 5 seções independentes (A–E). Cada seção possui uma tabela dinâmica de exercícios com funcionalidades de CRUD completo:</p><ul><li>Adicionar exercícios com nome, peso e repetições</li><li>Editar inline — clicando em editar, as células viram campos de texto editáveis</li><li>Deletar exercícios da tabela</li><li>Persistência com localStorage — os dados são salvos em JSON e sobrevivem ao recarregar a página</li></ul><p>Tudo feito com HTML5, CSS3 e JavaScript vanilla (sem frameworks).</p><br><p>Este projeto está atualmente em fase de testes fechados (closed testing) na Google Play, aguardando aprovação para publicação na Play Store. Todo o processo de empacotamento e configuração como aplicativo Android foi conduzido de forma independente.</p><p>Quer participar do programa de testes? Envie um e-mail para <strong>brunapessoa.bpm@gmail.com</strong> com o assunto <strong>"Plan B - Tester"</strong> e você será incluído(a) na lista de testers.</p>'

export const weatherPtBr = '<p><abbr title="HTML 5"><img src="images/icons/html5-200.png" alt="html-logo" class="skillsIcons"></abbr><abbr title="JavaScript"><img src="images/icons/javascript.svg" alt="js-logo" class="skillsIcons jsIcon"></abbr><abbr title="React"><img src="images/icons/react(1).png" alt="react-logo" class="skillsIcons reactIcon"></abbr><abbr title="Tailwind"><img src="images/icons/tailwindcss.svg" alt="tailwind-logo" class="skillsIcons tailwindIcon"></abbr></p><p>SPA de previsão do tempo construída com React, Vite e Tailwind CSS, consumindo as APIs WeatherAPI e Unsplash. Funcionalidades implementadas:</p><ul><li>Busca por cidade via formulário controlado, com suporte a clique e tecla Enter</li><li>Geolocalização do usuário ao carregar a página, via API nativa do navegador, com busca manual como alternativa</li><li>Alternância entre clima atual e previsão dos próximos 5 dias</li><li>Plano de fundo dinâmico — busca uma foto da cidade pesquisada via API da Unsplash</li><li>Estados de carregamento e erro com mensagens customizadas e renderização condicional</li><li>Lista de previsão organizada em CSS Grid, com colunas alinhadas de data, máxima e mínima</li></ul><p>Hooks utilizados: useState, useEffect. Estilização com Tailwind CSS, incluindo sobreposições translúcidas e text-shadow para contraste sobre as imagens de fundo.</p>'

export const tasksDescPtBr = '<p><abbr title="HTML 5"><img src="images/icons/html5-200.png" alt="html-logo" class="skillsIcons"></abbr><abbr title="JavaScript"><img src="images/icons/javascript.svg" alt="js-logo" class="skillsIcons jsIcon"></abbr> <abbr title="React"><img src="images/icons/react(1).png" alt="react-logo" class="skillsIcons reactIcon"></abbr><abbr title="React"><img src="images/icons/tailwindcss.svg" alt="tailwind-logo" class="skillsIcons tailwindIcon"></abbr></p><p>Aplicação de gerenciamento de tarefas (SPA) desenvolvida com React 19, React Router e Tailwind CSS. Funcionalidades implementadas:</p><ul><li>Adicionar tarefas com título e descrição via formulário controlado com validação básica</li><li>Marcar como concluída — altera visualmente a tarefa com riscado</li><li>Deletar tarefas por ID</li><li>Página de detalhes em rota separada, com dados passados via query params na URL</li><li>Persistência com localStorage via useEffect</li></ul><p>React hooks utilizados: useState, useEffect, useNavigate, useSearchParams. Arquitetura com estado centralizado no App.jsx e funções passadas como props para os componentes filhos.</p>'

export const recipesDescPtBr = '<p><abbr title="HTML 5"><img src="images/icons/html5-200.png" alt="html-logo" class="skillsIcons"></abbr><abbr title="JavaScript"><img src="images/icons/typescript-original.svg" alt="ts-logo" class="skillsIcons tsIcon"></abbr><abbr title="React"><img src="images/icons/react(1).png" alt="react-logo" class="skillsIcons reactIcon"></abbr><abbr title="Tailwind"><img src="images/icons/tailwindcss.svg" alt="tailwind-logo" class="skillsIcons tailwindIcon"></abbr></p><p>SPA de busca de receitas construída com React, Vite, TypeScript e Tailwind CSS, consumindo a API TheMealDB. Funcionalidades implementadas:</p><ul><li>Busca de receitas por nome via formulário controlado, com grid de cards responsivo exibindo nome, imagem, região e categoria da receita</li><li>Modal de detalhes aberto via estado, exibindo as informações completas da receita sem perder a posição de rolagem da lista</li><li>Lista de ingredientes/medidas renderizada dinamicamente, filtrando valores vazios ou nulos da resposta da API</li><li>Instruções divididas em parágrafos/passos legíveis em vez de um único bloco de texto</li><li>Estados de carregamento e erro com mensagens customizadas e renderização condicional</li></ul><p>Hooks utilizados: useState, useEffect. Estilização com Tailwind CSS, incluindo imagem de fundo customizada, Google Fonts e text-shadow para contraste sobre o fundo com foto.</p>'

export const footerPtBr = 'Bruna Pessoa Machado - Desenvolvedora de Software'
/* ====================================================== */

export const titleEng = 'Front-end Software Developer'

export const aboutMeEng = 'About me'
export const projectsEng = 'Projects'

export const detailsEng = '<p>Address: Eindhoven - Netherlands</p><p>E-mail: brunapessoa.bpm@gmail.com</p>'

export const aboutTxtEng = "<p>Brazilian Front-end developer, focused on building modern, responsive, and user-centered interfaces.</p><p>I develop functional and well-structured web applications using HTML, CSS, JavaScript, React, and Tailwind, with attention to detail.</p><p>After 5 years in the legal field, I bring to tech strong analytical thinking, organization, and a problem-solving mindset.</p>"

export const projectsTxtEng = 'You can access my projects`s  pages:'

export const planBDescEng = '<p><abbr title="HTML 5"><img src="images/icons/html5-200.png" alt="html-logo" class="skillsIcons"></abbr><abbr title="CSS 3"><img src="images/icons/css3-200.png" alt="css-logo"class="skillsIcons"></abbr><abbr title="JavaScript"><img src="images/icons/javascript.svg" alt="js-logo"class="skillsIcons jsIcon"></abbr></p><p> Client-side workout planner with 5 independent training sections (A–E). Each section features a dynamic exercise table with full CRUD functionality:</p><ul><li>Add exercises with name, weight, and reps</li><li>Inline editing — clicking edit converts cells into editable fields</li><li>Delete exercises from the table</li><li>localStorage persistence — data is saved as JSON and survives page reload</li></ul><p>Built with HTML5, CSS3, and vanilla JavaScript (no frameworks).</p><br><p>This project is currently in closed testing on Google Play, pending approval for release on the Play Store. The entire process of packaging and configuring it as an Android app was carried out independently.</p><p>Want to join the testing program? Send an email to <strong>brunapessoa.bpm@gmail.com</strong> with the subject <strong>"Plan B - Tester"</strong> and you\'ll be added to the tester list.</p>'

export const weatherDescEng = '<p><abbr title="HTML 5"><img src="images/icons/html5-200.png" alt="html-logo" class="skillsIcons"></abbr><abbr title="JavaScript"><img src="images/icons/javascript.svg" alt="js-logo" class="skillsIcons jsIcon"></abbr><abbr title="React"><img src="images/icons/react(1).png" alt="react-logo" class="skillsIcons reactIcon"></abbr><abbr title="Tailwind"><img src="images/icons/tailwindcss.svg" alt="tailwind-logo" class="skillsIcons tailwindIcon"></abbr></p><p>Weather forecast SPA built with React, Vite, and Tailwind CSS, consuming the WeatherAPI and Unsplash APIs. Features implemented:</p><ul><li>City search via a controlled form, supporting both click and Enter key submission</li><li>Geolocation on page load through the native browser API, with manual search as a fallback</li><li>Toggle between current weather and the 5-day forecast</li><li>Dynamic background — fetches a photo of the searched city via the Unsplash API</li><li>Loading and error states with custom messages and conditional rendering</li><li>Forecast list laid out with CSS Grid, aligning date, max, and min temperature columns</li></ul><p>React hooks used: useState, useEffect. Styled with Tailwind CSS, including translucent overlays and text-shadow for contrast over background images.</p>'

export const tasksDescEng = '<p><abbr title="HTML 5"><img src="images/icons/html5-200.png" alt="html-logo" class="skillsIcons"></abbr><abbr title="JavaScript"><img src="images/icons/javascript.svg" alt="js-logo" class="skillsIcons jsIcon"></abbr><abbr title="React"><img src="images/icons/react(1).png" alt="react-logo" class="skillsIcons reactIcon"></abbr><abbr title="Tailwind"><img src="images/icons/tailwindcss.svg" alt="tailwind-logo" class="skillsIcons tailwindIcon"></abbr></p><p>Task management SPA built with React 19, React Router, and Tailwind CSS. Features implemented:</p><ul><li>Add tasks with title and description via a controlled form with basic validation</li><li>Toggle completion — visual strikethrough feedback on completed tasks</li><li>Delete tasks by ID</li><li>Details page on a separate route, with task data passed via URL query params</li><li>localStorage persistence using useEffect</li></ul><p>React hooks used: useState, useEffect, useNavigate, useSearchParams. State centralized in App.jsx with mutation functions passed down as props to child components.</p>'


export const recipesDescEng = '<p><abbr title="HTML 5"><img src="images/icons/html5-200.png" alt="html-logo" class="skillsIcons"></abbr><abbr title="JavaScript"><img src="images/icons/typescript-original.svg" alt="ts-logo" class="skillsIcons tsIcon"></abbr><abbr title="React"><img src="images/icons/react(1).png" alt="react-logo" class="skillsIcons reactIcon"></abbr><abbr title="Tailwind"><img src="images/icons/tailwindcss.svg" alt="tailwind-logo" class="skillsIcons tailwindIcon"></abbr></p><p>Recipe search SPA built with React, Vite, TypeScript, and Tailwind CSS, consuming the TheMealDB API. Features implemented:</p><ul><li>Name-based recipe search via a controlled form Responsive card grid showing recipe name, image, area, and category</li><li>Detail modal opened by state, showing full recipe info without losing scroll position on the list</li><li>Dynamically rendered ingredients/measurements list, filtering out empty or null values from the API response</li><li>Instructions split into readable paragraphs/steps instead of a single text block</li><li>Loading and error states with custom messages and conditional rendering</li></ul><p>React hooks used: useState, useEffect. Styled with Tailwind CSS, including a custom background image, Google Fonts, and text-shadow for contrast over the photo background.</p>'

export const footerEng = 'Bruna Pessoa Machado - Software Developer'

/* ======================================================== */

export const titleNl = 'Front-end Softwareontwikkelaar'

export const aboutMeNl = 'Over mij'
export const projectsNl = 'Projecten'

export const detailsNl = '<p>Adres: Eindhoven - Nederland</p><p>E-mail: brunapessoa.bpm@gmail.com</p>'

export const aboutTxtNl = '<p>Braziliaanse front-end developer, gericht op het bouwen van moderne, responsieve en gebruiksvriendelijke interfaces.</p><p>Ik ontwikkel functionele en goed gestructureerde webapplicaties met HTML, CSS, JavaScript, React en Tailwind, met oog voor detail.</p><p>Na 5 jaar in de juridische sector breng ik naar de technologie sterk analytisch denkvermogen, organisatie en een probleemoplossende mindset.</p>'

export const projectsTxtNl = 'Je kunt de pagina`s van mijn projecten bekijken:'

export const planBDescNL = '<p><abbr title="HTML 5"><img src="images/icons/html5-200.png" alt="html-logo" class="skillsIcons"></abbr><abbr title="CSS 3"><img src="images/icons/css3-200.png" alt="css-logo" class="skillsIcons"></abbr><abbr title="JavaScript"><img src="images/icons/javascript.svg" alt="js-logo" class="skillsIcons jsIcon"></abbr></p><p> Client-side trainingsplanner met 5 onafhankelijke trainingssecties (A–E). Elke sectie bevat een dynamische oefentabel met volledige CRUD-functionaliteit:</p><ul><li>Toevoegen van oefeningen met naam, gewicht en herhalingen</li><li>Inline bewerken — klikken op bewerken zet cellen om in bewerkbare velden</li><li>Verwijderen van oefeningen uit de tabel</li><li>localStorage persistentie — gegevens worden opgeslagen als JSON en blijven bewaard na het herladen van de pagina</li></ul><p>Gebouwd met HTML5, CSS3 en vanilla JavaScript (geen frameworks).</p><br><p>Dit project bevindt zich momenteel in een gesloten testfase (closed testing) op Google Play, in afwachting van goedkeuring voor publicatie in de Play Store. Het volledige proces van verpakking en configuratie als Android-app is zelfstandig uitgevoerd.</p><p>Wil je deelnemen aan het testprogramma? Stuur een e-mail naar <strong>brunapessoa.bpm@gmail.com</strong> met als onderwerp <strong>"Plan B - Tester"</strong> en je wordt toegevoegd aan de testerslijst.</p>'

export const weatherDescNL = '<p><abbr title="HTML 5"><img src="images/icons/html5-200.png" alt="html-logo" class="skillsIcons"></abbr><abbr title="JavaScript"><img src="images/icons/javascript.svg" alt="js-logo" class="skillsIcons jsIcon"></abbr><abbr title="React"><img src="images/icons/react(1).png" alt="react-logo" class="skillsIcons reactIcon"></abbr><abbr title="Tailwind"><img src="images/icons/tailwindcss.svg" alt="tailwind-logo" class="skillsIcons tailwindIcon"></abbr></p><p>Weersvoorspellings-SPA gebouwd met React, Vite en Tailwind CSS, met gebruik van de WeatherAPI- en Unsplash-APIs. Geïmplementeerde functies:</p> <ul><li>Stadszoekfunctie via een controlled form, met ondersteuning voor zowel klikken als de Enter-toets</li><li>Geolocatie bij het laden van de pagina via de native browser-API, met handmatig zoeken als alternatief</li><li>Schakelen tussen het huidige weer en de 5-daagse voorspelling</li><li>Dynamische achtergrond — haalt een foto van de gezochte stad op via de Unsplash API</li><li>Laad- en foutstatussen met aangepaste berichten en voorwaardelijke weergave</li><li>Voorspellingslijst opgemaakt met CSS Grid, met uitgelijnde kolommen voor datum, max- en minimumtemperatuur</li></ul><p>Gebruikte React hooks: useState, useEffect. Gestyled met Tailwind CSS, inclusief doorzichtige overlays en text-shadow voor contrast op achtergrondafbeeldingen.</p>'

export const tasksDescNL = '<p><abbr title="HTML 5"><img src="images/icons/html5-200.png" alt="html-logo" class="skillsIcons"></abbr><abbr title="JavaScript"><img src="images/icons/javascript.svg" alt="js-logo" class="skillsIcons jsIcon"></abbr><abbr title="React"><img src="images/icons/react(1).png" alt="react-logo" class="skillsIcons reactIcon"></abbr><abbr title="Tailwind"><img src="images/icons/tailwindcss.svg" alt="tailwind-logo" class="skillsIcons tailwindIcon"></abbr></p><p>Taakbeheer SPA gebouwd met React 19, React Router en Tailwind CSS. Geïmplementeerde functionaliteiten:</p><ul><li>Toevoegen van taken met titel en beschrijving via een gecontroleerd formulier met basisvalidatie</li><li>Voltooiing markeren — visuele doorhaling bij voltooide taken</li><li>Verwijderen van taken op ID</li><li>Detailpagina op een aparte route, met taakgegevens doorgegeven via URL query params</li><li>localStorage persistentie met useEffect</li></ul><p>Gebruikte React hooks: useState, useEffect, useNavigate, useSearchParams. Status gecentraliseerd in App.jsx met mutatefuncties doorgegeven als props aan onderliggende componenten.</p>'

export const recipesDescNL = '<p><abbr title="HTML 5"><img src="images/icons/html5-200.png" alt="html-logo" class="skillsIcons"></abbr><abbr title="JavaScript"><img src="images/icons/typescript-original.svg" alt="ts-logo" class="skillsIcons tsIcon"></abbr><abbr title="React"><img src="images/icons/react(1).png" alt="react-logo" class="skillsIcons reactIcon"></abbr><abbr title="Tailwind"><img src="images/icons/tailwindcss.svg" alt="tailwind-logo" class="skillsIcons tailwindIcon"></abbr></p><p>Receptenzoek-SPA gebouwd met React, Vite, TypeScript en Tailwind CSS, met gebruik van de TheMealDB API. Geïmplementeerde functies:</p><ul><li>Receptenzoek op naam via een gecontroleerd formulier, met een responsieve kaartweergave die naam, afbeelding, regio en categorie toont</li><li>Detailmodaal geopend via state, met volledige receptinformatie zonder verlies van scrollpositie in de lijst</li><li>Dynamisch weergegeven ingrediënten-/hoeveelhedenlijst, waarbij lege of null-waarden uit de API-respons worden gefilterd</li><li>Instructies opgesplitst in leesbare paragrafen/stappen in plaats van één tekstblok</li><li>Laad- en foutstatussen met aangepaste berichten en voorwaardelijke weergave</li></ul><p>Gebruikte React hooks: useState, useEffect. Gestyled met Tailwind CSS, inclusief een aangepaste achtergrondafbeelding, Google Fonts en text-shadow voor contrast op de foto-achtergrond.</p>'

export const footerNl = 'Bruna Pessoa Machado – Softwareontwikkelaar';